services:
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: ${DB_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      TZ: ${TZ}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    restart: always
    networks:
      - capif-net

  redis:
    image: redis:7.4.2-alpine3.21
    container_name: ${REDIS_NAME:-redis}
    restart: always
    ports:
      - '6379:6379'
    environment:
      TZ: ${TZ}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - capif-net

volumes:
  postgres_data:  

networks:
  capif-net:
    driver: bridge
