services:
  app:
    build: .
    container_name: capif-back
    environment:
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      TZ: ${TZ}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    networks:
      - app-network
    restart: always

  redis:
    image: redis:7.4.2-alpine3.21
    container_name: redis
    environment:
      TZ: ${TZ}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge